version: '3'
services:
  node:
    build: ./docker
    image: base/node:10.16-alpine
    environment: 
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=80
    command: "yarn run dev"
    volumes:
      - ./app:/app
    ports:
      - "80:80"